# Copyright Gino Valente 2017

title: Gino Valente
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# User Settings
email: gino.valente3@gmail.com
twitter_username: ginovalente
github_username:  gvalente
instagram_username: gvalente

# Project settings
collections:
  projects:
    output: true

markdown: kramdown
project-wrapper: wrapper project-content col-sm-11 middle-sm col-med-8 col-xlrg-7
